//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class MessageType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.SenderType SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.RecipientType RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.OriginatorType OriginatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.ServiceType ServiceField;
        
        private Client.Service.TypeCodeType TypeCodeField;
        
        private Client.Service.StatusType StatusField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginRequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        private int ExchangeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OKTMOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.SubMessageType[] SubMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.Service.SenderType Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.Service.RecipientType Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.Service.OriginatorType Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Client.Service.ServiceType Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Client.Service.TypeCodeType TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((this.TypeCodeField.Equals(value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public Client.Service.StatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RequestIdRef {
            get {
                return this.RequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdRefField, value) != true)) {
                    this.RequestIdRefField = value;
                    this.RaisePropertyChanged("RequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string OriginRequestIdRef {
            get {
                return this.OriginRequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginRequestIdRefField, value) != true)) {
                    this.OriginRequestIdRefField = value;
                    this.RaisePropertyChanged("OriginRequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int ExchangeType {
            get {
                return this.ExchangeTypeField;
            }
            set {
                if ((this.ExchangeTypeField.Equals(value) != true)) {
                    this.ExchangeTypeField = value;
                    this.RaisePropertyChanged("ExchangeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TestMsg {
            get {
                return this.TestMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.TestMsgField, value) != true)) {
                    this.TestMsgField = value;
                    this.RaisePropertyChanged("TestMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OKTMO {
            get {
                return this.OKTMOField;
            }
            set {
                if ((object.ReferenceEquals(this.OKTMOField, value) != true)) {
                    this.OKTMOField = value;
                    this.RaisePropertyChanged("OKTMO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public Client.Service.SubMessageType[] SubMessage {
            get {
                return this.SubMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SubMessageField, value) != true)) {
                    this.SubMessageField = value;
                    this.RaisePropertyChanged("SubMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class SenderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipientType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class RecipientType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OriginatorType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class OriginatorType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class ServiceType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MnemonicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mnemonic {
            get {
                return this.MnemonicField;
            }
            set {
                if ((object.ReferenceEquals(this.MnemonicField, value) != true)) {
                    this.MnemonicField = value;
                    this.RaisePropertyChanged("Mnemonic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeCodeType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    public enum TypeCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GSRV = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFNC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    public enum StatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCEPT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCEL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILURE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTIFY = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PACKET = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PING = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PROCESS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REJECT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATE = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubMessageType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class SubMessageType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubRequestNumberField;
        
        private Client.Service.StatusType StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.OriginatorType OriginatorField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginRequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubRequestNumber {
            get {
                return this.SubRequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubRequestNumberField, value) != true)) {
                    this.SubRequestNumberField = value;
                    this.RaisePropertyChanged("SubRequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Client.Service.StatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.Service.OriginatorType Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OriginRequestIdRef {
            get {
                return this.OriginRequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginRequestIdRefField, value) != true)) {
                    this.OriginRequestIdRefField = value;
                    this.RaisePropertyChanged("OriginRequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RequestIdRef {
            get {
                return this.RequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdRefField, value) != true)) {
                    this.RequestIdRefField = value;
                    this.RaisePropertyChanged("RequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDataType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class MessageDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.AppDataType AppDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.AppDocumentType AppDocumentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.Service.AppDataType AppData {
            get {
                return this.AppDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDataField, value) != true)) {
                    this.AppDataField = value;
                    this.RaisePropertyChanged("AppData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.Service.AppDocumentType AppDocument {
            get {
                return this.AppDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDocumentField, value) != true)) {
                    this.AppDocumentField = value;
                    this.RaisePropertyChanged("AppDocument");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppDataType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    public partial class AppDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppDocumentType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.MessageType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.SenderType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.RecipientType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.OriginatorType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.ServiceType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.TypeCodeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.StatusType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.SubMessageType[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.SubMessageType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.MessageDataType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.AppDataType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.ItemsChoiceType[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Service.ItemsChoiceType))]
    public partial class AppDocumentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.ArrayOfAnyType ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Service.ItemsChoiceType[] ItemsElementNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.Service.ArrayOfAnyType Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.Service.ItemsChoiceType[] ItemsElementName {
            get {
                return this.ItemsElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsElementNameField, value) != true)) {
                    this.ItemsElementNameField = value;
                    this.RaisePropertyChanged("ItemsElementName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://smev.gosuslugi.ru/rev020415", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemsChoiceType", Namespace="http://smev.gosuslugi.ru/rev020415")]
    public enum ItemsChoiceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BinaryData = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DigestValue = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reference = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smev.gosuslugi.ru/rev020415", ConfigurationName="Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://smev.gosuslugi.ru/rev020415/IService/GetData", ReplyAction="http://smev.gosuslugi.ru/rev020415/IService/GetDataResponse")]
        Client.Service.Response GetData(Client.Service.Request request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://smev.gosuslugi.ru/rev020415/IService/GetData", ReplyAction="http://smev.gosuslugi.ru/rev020415/IService/GetDataResponse")]
        System.Threading.Tasks.Task<Client.Service.Response> GetDataAsync(Client.Service.Request request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Request", WrapperNamespace = "http://smev.gosuslugi.ru/rev020415", IsWrapped = true)]
    public partial class Request
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://smev.gosuslugi.ru/rev020415", Order = 0)]
        public Client.Service.MessageType Message;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://smev.gosuslugi.ru/rev020415", Order = 1)]
        public Client.Service.MessageDataType MessageData;

        public Request()
        {
        }

        public Request(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData)
        {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smev.gosuslugi.ru/rev020415")]
    public partial class RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.Service.MessageType Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.Service.MessageDataType MessageData;
        
        public RequestBody() {
        }
        
        public RequestBody(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Response", Namespace="http://smev.gosuslugi.ru/rev020415", Order=0)]
        public Client.Service.ResponseBody Body;
        
        public Response() {
        }
        
        public Response(Client.Service.ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://smev.gosuslugi.ru/rev020415")]
    public partial class ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.Service.MessageType Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.Service.MessageDataType MessageData;
        
        public ResponseBody() {
        }
        
        public ResponseBody(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.Service.IService>, Client.Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.Response Client.Service.IService.GetData(Client.Service.Request request) {
            return base.Channel.GetData(request);
        }
        
        public void GetData(ref Client.Service.MessageType Message, ref Client.Service.MessageDataType MessageData) {
            Client.Service.Request inValue = new Client.Service.Request();
            inValue = new Client.Service.Request();
            inValue.Message = Message;
            inValue.MessageData = MessageData;
            Client.Service.Response retVal = ((Client.Service.IService)(this)).GetData(inValue);
            Message = retVal.Body.Message;
            MessageData = retVal.Body.MessageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Service.Response> Client.Service.IService.GetDataAsync(Client.Service.Request request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Service.Response> GetDataAsync(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData) {
            Client.Service.Request inValue = new Client.Service.Request();
            inValue = new Client.Service.Request();
            inValue.Message = Message;
            inValue.MessageData = MessageData;
            return ((Client.Service.IService)(this)).GetDataAsync(inValue);
        }
    }
}
